### ISSUE TITLE
LICENSE file is confused: GPLv1+ or GPLv2+ ?

### ISSUE THREAD

**Issue by vapier** [shlomif/perl-error.pm#1]
the LICENSE file says:
```
Terms of Perl itself

a) the GNU General Public License as published by the Free
   Software Foundation; either version 1, or (at your option) any
   later version, or
b) the "Artistic License"

----------------------------------------------------------------------------

                    GNU GENERAL PUBLIC LICENSE
                       Version 2, June 1991
```

is the inlined GNU license just a mistake and it should actually be Version 1 ?

**Comment by shlomif** [comment]
https://en.wikipedia.org/wiki/IANAL

Programming today is a race between software engineers striving to build
bigger and better idiot-proof programs, and the Universe trying to produce
bigger and better idiots. So far, the Universe is winning.

    -- Rick Cook
    -- The Wizardry Compiled
    -- https://en.wikiquote.org/wiki/Rick_Cook

Use of Error.pm is discouraged anyway.

**Comment by vapier** [comment]
the license file isn't changed so i don't see why this has been marked complete. do you want me to send you a PR to fix it?

**Comment by shlomif** [comment]
> the license file isn't changed so i don't see why this has been marked complete. do you want me to send you a PR to fix it?

No! http://shlomifishswiki.branchable.com/Never_Try_to_Please_Everyone/ . go away

**Comment by vapier** [comment]
is it that you don't understand how licensing works?
