### ISSUE TITLE
clarify use of MIT license

### ISSUE THREAD

**Issue by vapier** [shlomif/perl-error.pm#2]
the Error.pm file says:
```
# This file is free software; you can redistribute it and/or
# modify it under the terms of the MIT/X11 license (whereas the licence
# of the Error distribution as a whole is the GPLv1+ and the Artistic
# licence).
```

i read this to mean:
* if i copy just Simple.pm around, it's MIT
* if i copy the entire Error module distribution, it's Artistic||GPLv1+, not MIT

or is the intention that the entire Error module distribution have combined license of ((Artistic || GPLv1+) && MIT) ?

can the LICENSE file please clarify this ?

**Comment by shlomif** [comment]
https://en.wikipedia.org/wiki/IANAL

Programming today is a race between software engineers striving to build
bigger and better idiot-proof programs, and the Universe trying to produce
bigger and better idiots. So far, the Universe is winning.

    -- Rick Cook
    -- The Wizardry Compiled
    -- https://en.wikiquote.org/wiki/Rick_Cook

Use of Error.pm is discouraged anyway.

**Comment by vapier** [comment]
i can send you a PR if you just clarify your intentions. if you're the sole author/copyright owner of the file in question, you don't have to be a lawyer. you can decide what license to use and how.

**Comment by shlomif** [comment]
On Fri, 23 Sep 2022 23:39:28 -0700
Mike Frysinger ***@***.***> wrote:

> i can send you a PR if you just clarify your intentions. if you're the sole
> author/copyright owner of the file in question, you don't have to be a
> lawyer. you can decide what license to use and how.
> 

you're wasting my time. please leave me and error.pm alone.

-- 

Shlomi Fish       https://www.shlomifish.org/
https://www.shlomifish.org/humour/bits/Google-Discontinues-Services/

Ken: [to Sarah] And who are you?
Sarah: I’m Sarah Eisenman. A Jewish vampire slayer. And who are you?
Ken: …Bitch!
    — https://www.shlomifish.org/humour/Buffy/A-Few-Good-Slayers/

Please reply to list if it's a mailing list post - https://shlom.in/reply .

**Comment by vapier** [comment]
i understand not everyone understands how copyright/licensing works.  that's fine.  i can help you figure out the right settings for however you want to manage the project.

**Comment by shlomif** [comment]
On Sat, 24 Sep 2022 03:31:20 -0700
Mike Frysinger ***@***.***> wrote:

> i understand not everyone understands how copyright/licensing works.  that's
> fine.  i can help you figure out the right settings for however you want to
> manage the project.
> 

i'm not interested. please freakin' leave us alone. i have a lot on my mind:

https://www.shlomifish.org/philosophy/culture/multiverse-cosmology/#see-also



-- 

Shlomi Fish       https://www.shlomifish.org/
https://www.shlomifish.org/humour/bits/New-versions-of-the-GPL/

Chuck Norris does not believe in Astrology, despite the fact that he is a
Pisces, and that Pisces always believe in Astrology.
    — https://www.shlomifish.org/humour/bits/facts/Chuck-Norris/

Please reply to list if it's a mailing list post - https://shlom.in/reply .

**Comment by vapier** [comment]
i understand you're busy.  i'll send a PR to fix the issues.

**Comment by shlomif** [comment]
On Sat, 24 Sep 2022 08:58:22 -0700
Mike Frysinger ***@***.***> wrote:

> i understand you're busy.  i'll send a PR to fix the issues.
> 

Dear Mike,

1. I will probably close your pullreq.

2. I think your complaints are nonsensical.

3. error.pm is deprecated anyway.

4. Get lost!!

-- 

Shlomi Fish       https://www.shlomifish.org/
Freecell Solver - https://fc-solve.shlomifish.org/

The Angel of Death cannot keep up with Chuck Norris’s throughput of killing.
    — https://www.shlomifish.org/humour/bits/facts/Chuck-Norris/

Please reply to list if it's a mailing list post - https://shlom.in/reply .
